# Generated by Django 3.0.2 on 2021-06-01 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffee',
            new_name='Donation',
        ),
    ]
